# Generated by Django 4.2.7 on 2023-11-10 17:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_farmerprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='farmerprofile',
            managers=[
                ('farmer', django.db.models.manager.Manager()),
            ],
        ),
    ]
