# Generated by Django 4.2.7 on 2023-11-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_farmerprofile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='farmerprofile',
            managers=[
            ],
        ),
    ]
