# Generated by Django 4.2.7 on 2023-11-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_farmerprofile_farmerlandinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerlandinformation',
            name='barangay',
            field=models.CharField(help_text='Enter land location barangay', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='hectares',
            field=models.IntegerField(help_text='Enter land size in hectares', null=True),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='image',
            field=models.ImageField(null=True, upload_to='land/'),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='location',
            field=models.TextField(help_text='Enter land location', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='lot_number',
            field=models.CharField(help_text='Enter land lot number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='province',
            field=models.CharField(help_text='Enter land provice', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='region',
            field=models.CharField(help_text='Enter land location region', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='square_meter',
            field=models.PositiveBigIntegerField(help_text='Enter land size square meter', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(help_text='Enter your mobile number', max_length=150, null=True),
        ),
    ]
