# Generated by Django 4.2.7 on 2023-11-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_farmerlandinformation_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerlandinformation',
            name='location',
        ),
    ]
