# Generated by Django 4.2.7 on 2023-11-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_farmerlandinformation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerlandinformation',
            name='municipality',
            field=models.CharField(help_text='Enter land location municipality', max_length=150, null=True),
        ),
    ]
