# Generated by Django 4.2.7 on 2023-12-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_gender_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerlandinformation',
            name='lat',
            field=models.FloatField(help_text='Enter land latitude', null=True),
        ),
        migrations.AddField(
            model_name='farmerlandinformation',
            name='long',
            field=models.FloatField(help_text='Enter land longitude', null=True),
        ),
    ]
