# Generated by Django 4.2.7 on 2023-12-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_farmerlandinformation_lat_farmerlandinformation_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerlandinformation',
            name='hectares',
            field=models.FloatField(help_text='Enter land size in hectares', null=True),
        ),
    ]
