# Generated by Django 4.2.7 on 2023-11-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_farmerlandinformation_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('date_added', models.DateTimeField(auto_created=True)),
                ('operation_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('operation_name', models.CharField(help_text='Required, enter operation name here', max_length=255)),
                ('operation_status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE')], max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('schedule_date', models.DateTimeField(help_text='Required, enter schedule date here')),
                ('schedule_status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE')], help_text='Required, select schedule status here', max_length=155)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('reservation_status', models.CharField(choices=[('DONE OPERATION', 'DONE OPERATION'), ('ONGOING OPERATION', 'ONGOING OPERATION')], help_text='Required, select if the operation status', max_length=155)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.OneToOneField(help_text='Required, select user here', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer')),
                ('schedule_id', models.ForeignKey(help_text='Required, select schedule here', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('reservation_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('payment_amount', models.CharField(help_text='Reqired, enter here amount paid', max_length=255)),
                ('balance', models.CharField(help_text='Reqired, enter here if there is a payment balance', max_length=255)),
                ('payment_type', models.CharField(choices=[('FULL PAID', 'FULL PAID'), ('HALF PAID', 'HALF PAID')], help_text='Required, select what type of payment', max_length=155)),
                ('farmer', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer')),
                ('operation', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.operation')),
            ],
        ),
    ]
