# Generated by Django 4.2.7 on 2023-11-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_gender_alter_user_role'),
        ('main_app', '0002_alter_operation_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.CharField(help_text='Required, enter here if there is a payment balance', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='farmer',
            field=models.OneToOneField(default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operation',
            field=models.OneToOneField(default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.operation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL PAID', 'FULL PAID'), ('HALF PAID', 'HALF PAID')], default='', help_text='Required, select what type of payment', max_length=155),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='farmer',
            field=models.OneToOneField(default='', help_text='Required, select user here', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='authentication.farmer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('DONE OPERATION', 'DONE OPERATION'), ('ONGOING OPERATION', 'ONGOING OPERATION')], default='', help_text='Required, select if the operation status', max_length=155),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='schedule_id',
            field=models.ForeignKey(default='', help_text='Required, select schedule here', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule'),
        ),
    ]
