# Generated by Django 4.2.7 on 2023-11-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_reservation_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='operation_id',
            field=models.ForeignKey(blank=True, default='', help_text='Required, select operation here', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.operation'),
        ),
    ]
