# Generated by Django 4.2.7 on 2023-11-12 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_reservation_operation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='reservation_id',
            new_name='payment_id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='operation_id',
            field=models.ForeignKey(default='', help_text='Required, select operation here', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.operation'),
        ),
    ]
