# Generated by Django 4.2.7 on 2023-11-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation',
            field=models.CharField(choices=[('NOT CONFIRM', 'NOT CONFIRM'), ('CONFIRMED', 'CONFIRMED')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.CharField(help_text='Optional if half payment only, enter here if there is a payment balance', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('ONGOING OPERATION', 'ONGOING OPERATION'), ('DONE OPERATION', 'DONE OPERATION')], default='', help_text='Required, select if the operation status', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='schedule_id',
            field=models.ForeignKey(default='', help_text='Required, select schedule here. If empty no available schedule.', limit_choices_to={'schedule_status': 'AVAILABLE'}, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule'),
        ),
    ]
