# Generated by Django 4.2.7 on 2023-11-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_reservation_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('CANCEL', 'CANCEL')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], default='PENDING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='schedule_id',
            field=models.ForeignKey(default='', help_text='Required, select schedule here. If empty no available schedule.', limit_choices_to={'schedule_status': 'AVAILABLE'}, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule'),
        ),
    ]
