# Generated by Django 4.2.7 on 2023-12-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_operation_options_reservation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eqiupment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('eqiupment_name', models.CharField(help_text='Required, enter equipment name here', max_length=255)),
                ('eqiupment_status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE')], default='', max_length=155)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
