# Generated by Django 4.2.7 on 2023-12-09 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_reservation_schedule_id_reservation_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='equipment',
            field=models.ForeignKey(default='', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.equipment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='schedule',
            field=models.DateField(help_text='Required, add your schedule here.', null=True),
        ),
    ]
