# Generated by Django 4.2.7 on 2023-12-09 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_payment_equipment_alter_reservation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
