# Generated by Django 4.2.7 on 2023-12-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_payment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=50, null=True),
        ),
    ]
