# Generated by Django 4.2.7 on 2023-12-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_reservation_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='operation',
        ),
    ]
