# Generated by Django 4.2.7 on 2023-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_payment_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='schedule',
            field=models.DateTimeField(help_text='Required, add your schedule here.', null=True),
        ),
    ]
