# Generated by Django 4.2.7 on 2023-12-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_reservation_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='schedule',
            field=models.DateField(help_text='Required, add your schedule here.', null=True),
        ),
    ]
