# Generated by Django 4.2.7 on 2023-12-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_reservation_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='equipment',
            field=models.ForeignKey(default='', help_text='Select equipment for operation.', limit_choices_to={'eqiupment_status': 'AVAILABLE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.equipment'),
        ),
    ]
