# Generated by Django 4.2.7 on 2023-12-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_payment_equipment_remove_payment_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('FULLY PAID', 'FULLY PAID')], max_length=150, null=True),
        ),
    ]
