# Generated by Django 4.2.7 on 2023-12-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_reservation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(default='', limit_choices_to={'payment_status': 'FULLY PAID'}, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('CANCEL', 'CANCEL')], default='', max_length=150, null=True),
        ),
    ]
