# Generated by Django 4.2.7 on 2023-12-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_payment_reservation_alter_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
