# Generated by Django 4.2.7 on 2023-12-29 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_payment_payment_type_alter_payment_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL PAID', 'FULL PAID'), ('HALF PAID', 'HALF PAID')], default='', help_text='Required, select what type of payment', max_length=155),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='main_app.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('UNPAID', 'UNPAID'), ('HALF PAID', 'HALF PAID'), ('FULLY PAID', 'FULLY PAID')], default='UNPAID', max_length=150, null=True),
        ),
    ]
