# Generated by Django 4.2.7 on 2024-01-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_payment_payment_type_alter_payment_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(help_text='Required, add your end date here.', null=True),
        ),
    ]
